### ISSUE TITLE
Fail if $EDITOR is not set (or do something sensible)

### ISSUE THREAD

**Issue by mattwynne** [tooky/retro-tools#4] opened 2020-05-26 11:30 UTC
I am trying out [a new shell](https://fishshell.com/) and I didn't have `$EDITOR` set.

I got this:

```
> retro add
/Users/matt/projects/retro-tools/src/retro-add: line 23: doc/retro/2020/05/26.md: Permission denied
```

When I fixed the `$EDITOR` it worked. I think it just needs a better error message - `Please set $EDITOR` or something.

Interestingly, I hadn't noticed this as `git` has somehow figured out which editor to use.

**Comment by aslakhellesoy** [comment] 2020-05-26 15:03
Dupe of #2 which is fixed.

**Closed as completed** 2020-05-26 16:51 UTC

**Comment by tooky** [comment] 2020-05-26 18:22
@mattwynne I wonder, do you have `$VISUAL` set? Is that how `git` figured it out?

**Comment by mattwynne** [comment] 2020-05-26 21:11
No I don't, but I see from the docs that:

> By default, Git uses whatever you’ve set as your default text editor via one of the shell environment variables VISUAL or EDITOR, **or else falls back to the vi editor** to create and edit your commit and tag messages. To change that default to something else, you can use the core.editor setting:
